# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  external_lxc = {
    pname = "external_lxc";
    version = "4e3a3630fff3dc04e0d4a761309f87f248e40b17";
    src = fetchFromGitHub {
      owner = "Linux-on-droid";
      repo = "external_lxc";
      rev = "4e3a3630fff3dc04e0d4a761309f87f248e40b17";
      fetchSubmodules = false;
      sha256 = "sha256-lh/YEh1ubAW51GKFZiraQZqbGGkdT6zuSVunDRAaKbE=";
    };
    date = "2024-11-24";
  };
  libhybris = {
    pname = "libhybris";
    version = "419f3ff6736e01cb0e579f65a34c85cfa7de578b";
    src = fetchFromGitHub {
      owner = "Linux-on-droid";
      repo = "libhybris";
      rev = "419f3ff6736e01cb0e579f65a34c85cfa7de578b";
      fetchSubmodules = false;
      sha256 = "sha256-h9QmJ/uZ2sHMGX3/UcxD+xe/myONacKwoBhmn0RK5sI=";
    };
    date = "2024-10-14";
  };
  vendor_lindroid_21 = {
    pname = "vendor_lindroid_21";
    version = "448abc3c437d5101cf42770045fe8796efdf28ed";
    src = fetchFromGitHub {
      owner = "Linux-on-droid";
      repo = "vendor_lindroid";
      rev = "448abc3c437d5101cf42770045fe8796efdf28ed";
      fetchSubmodules = false;
      sha256 = "sha256-bmDeDe23VX9M74rfAOuYJWTkkZ5No8o10j5q2XKgGkk=";
    };
    date = "2024-11-24";
  };
  vendor_lindroid_22_1 = {
    pname = "vendor_lindroid_22_1";
    version = "d7c9e416b3de6ba3e06f07c553a2390ae14054fe";
    src = fetchFromGitHub {
      owner = "Linux-on-droid";
      repo = "vendor_lindroid";
      rev = "d7c9e416b3de6ba3e06f07c553a2390ae14054fe";
      fetchSubmodules = false;
      sha256 = "sha256-KvIedX6Nhta77AGPJcgHW/1zJS/9Vaajr/MHHcvDT7k=";
    };
    date = "2025-04-12";
  };
}
