name: "Update LineageOS"

on: 
  schedule: 
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  updates:
    strategy:
      matrix:
        include:
          - branch: "lineage-22.1"
            flavor: "lineageos"
          - branch: "lineage-21.0"
            flavor: "lineageos"
    name: "Update ${{ matrix.branch }} (${{ matrix.flavor }})"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Update
      run: |
        nix develop -c ./flavors/lineageos/update.sh "${{ matrix.branch }}"

    - name: Create LineageOS Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "LineageOS(${{ matrix.branch }}): Auto Update"
        title: "[LineageOS ${{ matrix.branch }}] System Update"
        branch: "lineageos-update/${{ matrix.branch }}-$(date +%s)"
        delete-branch: true
        labels: "automated,lineageos"

    - name: Output PR Info
      run: |
        echo "Branch: ${{ matrix.branch }}"
        echo "Flavor: ${{ matrix.flavor }}"
        echo "PR Number: ${{ steps.cpr.outputs.pull-request-number }}"
        echo "PR URL: ${{ steps.cpr.outputs.pull-request-url }}"