name: "Build LineageOS"

on: 
  schedule: 
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - device: "pstar"
            system: "lineageos"
          # - device: "another_device"
          #   system: "lineageos"
    name: "Build ${{ matrix.device }} (${{ matrix.system }})"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: |
        cd template
        nix build .#"${{ matrix.device }}_${{ matrix.system }}" -o "${{ matrix.device }}_${{ matrix.system }}"

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "${{ matrix.device }}_${{ matrix.system }}"
        path: "template/${{ matrix.device }}_${{ matrix.system }}"